### ISSUE TITLE
The dataset link of  PETCT is the same with CET 

### ISSUE THREAD

**Issue by CodingMice** [wentaozhu/AnatomyNet-for-anatomical-segmentation#1]

**Comment by wentaozhu** [comment]
Thank you very much for your interest!

Now it should be fine.

**Comment by CodingMice** [comment]
Thank you!  I have great interest in your work. And I try to run your code now. May I ask you some question?  Could you please tell me your Wechat number?




| |
王文琪
邮箱：wwenki1992@163.com
|

签名由 网易邮箱大师 定制

On 01/10/2019 12:08, Wentao Zhu wrote:

Thank you very much for your interest!

Now it should be fine.

**Comment by wentaozhu** [comment]
I prefer GitHub to report issues so that other people can help us and we can help others as well. My wechat is zhuwentao_1991. We can be friends by wechat.
