### ISSUE TITLE
How did you pre-process the Data? I mean, how did you convert the dicom images to numpy arrays....

### ISSUE THREAD

**Issue by Bharat-Reddy** [wentaozhu/AnatomyNet-for-anatomical-segmentation#10]
Just curious about what all techniques did you use....

**Comment by wentaozhu** [comment]
It is in https://github.com/wentaozhu/AnatomyNet-for-anatomical-segmentation/blob/master/src/preprocess_crop.ipynb

**Comment by Bharat-Reddy** [comment]
Oops... didn't see that
Thanks!
