### ISSUE TITLE
Is the trained-model saved somewhere, in drive or cloud?? Its taking too long to train

### ISSUE THREAD

**Issue by Bharat-Reddy** [wentaozhu/AnatomyNet-for-anatomical-segmentation#12]
I wanna run the model on the data that I have, but the training is taking too long(even after using Google Colab GPU). Can you please share the trained model....

**Comment by wentaozhu** [comment]
I guess you can finish the training within one day. I am so sorry that I do not have the pretrained model. You can train the model on your own dataset.

**Comment by Bharat-Reddy** [comment]
Alright
