### ISSUE TITLE
Model is not training for 3rd organ(Mandible)

### ISSUE THREAD

**Issue by Bharat-Reddy** [wentaozhu/AnatomyNet-for-anatomical-segmentation#13]
loss:   0%|          | 0/88 [00:00<?, ?it/s]

epoch 37 TRAIN loss 2.8312
test loss 0.8429, 0.4998, 0.0000, 0.6772, 0.6740, 0.8516, 0.8249, 0.7296, 0.7656
best test loss 0.8437, 0.5580, 0.0000, 0.7028, 0.7022, 0.8647, 0.8469, 0.7699, 0.7822

As you can see the loss is 0 for 3rd organ.
Any idea why this is happening?

**Comment by wentaozhu** [comment]
Maybe you need to train longer. Empirically, some organs are 0 and you will get reasonable results after you train longer.

**Comment by Bharat-Reddy** [comment]
I see, just to give a little bit of more insight, I got a non-zero value when I trained with only PDDCA18 data. Now when I'm training with PDDCA18+HNCetuximab data I'm getting this 0 loss.

**Comment by Bharat-Reddy** [comment]
And the problem is that if I have this 0 loss the model weights corresponding to 3rd organ is not saved. Although that's not an issue in this case because I have weights saved corresponding to other organs, but just thought of confirming with you that its not an issue.

**Comment by wentaozhu** [comment]
How many epoch did you use? Try to train longer time.

**Comment by Bharat-Reddy** [comment]
I trained it for 80 epochs with **RMSprop** optimizer. It took many hours for it to train.

**Comment by wentaozhu** [comment]
In my code, I trained for 200 epochs. Did you use hybrid loss between dice and focal?

**Comment by Bharat-Reddy** [comment]
I didn't change any code except the paths and did a little bit of image resizing.
I've trained **baselineSERes18Conc.py**

**Comment by wentaozhu** [comment]
The dice loss is implemented in https://github.com/wentaozhu/AnatomyNet-for-anatomical-segmentation/blob/master/src/AnatomyNet.py . Please use hybrid loss as described in the paper. AnatomyNet: Deep Learning for Fast and Fully Automated Whole‐volume Segmentation of Head and Neck Anatomy. Medical physics (2018).
