### ISSUE TITLE
About Pytorch version

### ISSUE THREAD

**Issue by qiuLimoges** [wentaozhu/AnatomyNet-for-anatomical-segmentation#16]
HI,
I am very intersted in your AnatomyNet et want to test it. But I see that the pytorch version is 0.3/0.4 which is a lettre old. I don't know if it can be used in my pytorch 1.3.1 environnement. ou do you have the plan to re compile it to the lastest version?
Think you for you attention.

**Comment by wentaozhu** [comment]
You can use pytorch 1.3.1 and it can run successfully.

**Comment by qiuLimoges** [comment]
Hi,
think you for your answers. I have tried your code but can not load correctly the dataset. I have downloaded the dataset PDDCA (version 1.4.1), tried to use preprocess_crop.ipynb to trait the data. It seems that nothing happened. 
Could you tell me how to start is? thinks a lot

**Comment by wentaozhu** [comment]
You don't need to run preprocessing. The data has been processed.

**Comment by qiuLimoges** [comment]
Hello,
the PDDCA data has the structure like '0522c0001/structures/Brainstem.nrrd, img.nrrd files.
but running AnatomyNet.py, the code search for folds like '/data/wtzhu/dataset/HNCetuximabclean/'
Also at the beginning of the code, you have defined the TRAIN TEST CET PET PATH like
TRAIN_PATH = './data/trainpddca15_crp_v2_pool1.pth'
TEST_PATH = './data/testpddca15_crp_v2_pool1.pth'
CET_PATH = './data/trainpddca15_cet_crp_v2_pool1.pth'
PET_PATH = './data/trainpddca15_pet_crp_v2_pool1.pth'
How can I find these?

Thank you for your patience.

**Comment by wentaozhu** [comment]
These *_PATH is the generated result. You just need to create a data directory and it can run automatically.

**Comment by qiuLimoges** [comment]
so at which place? under the ./data subfolder? how to name it?
Need I give the data directory as parameter of AnatomyNet.py
Thinks

**Comment by wentaozhu** [comment]
Yes.

**Comment by qiuLimoges** [comment]
sorry I can't run your code. have I any guide or manuel for the beginner?
Thanks

**Comment by wentaozhu** [comment]
What is your error?

**Comment by qiuLimoges** [comment]
HI, this is part of the error msg:

missing annotation Submandibular_L 0522c0669
missing annotation Submandibular_R 0522c0669
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "AnatomyNet.py", line 160, in <module>
    train_data, test_data = process('./data/wtzhu/dataset/pddca18/')
  File "AnatomyNet.py", line 146, in process
    return getdatamask(train_data+train_dataopt+test_data,                        train_masks_data+train_masks_dataopt+test_masks_data,debug=debug),            getdatamask(test_dataoff, test_masks_dataoff,debug=debug)
  File "AnatomyNet.py", line 96, in getdatamask
    img = np.load(fnm) # z y x
  File "/home/hao/anaconda3/envs/tf/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: **'./data/wtzhu/dataset/pddca18/0522c0009/img_crp_v2.npy'**

**Comment by wentaozhu** [comment]
You need to change the data path to your own path for the dataset.
