### ISSUE TITLE
Question regarding fdl_loss_wmask implementation.

### ISSUE THREAD

**Issue by jmarsil** [wentaozhu/AnatomyNet-for-anatomical-segmentation#17]
I'm trying to use this loss in my segmentation task. Could you describe what the structure of inputs, targets and flagvec should be? Much thanks!

**Comment by wentaozhu** [comment]
The input is the 3D image, target is the 4D classification mask with one dimension represents different classes, flagvec is 1 if the training provides all the labels of classes and otherwise 0. Please read the paper and get familiar with the work first https://arxiv.org/pdf/1808.05238.pdf
