### ISSUE TITLE
关于preprocess的遇到一点问题

### ISSUE THREAD

**Issue by wwwwwuxueyu** [wentaozhu/AnatomyNet-for-anatomical-segmentation#18]
RuntimeError: Exception thrown in SimpleITK ReadImage: /opt/miniconda2/conda-bld/simpleitk_1491574810448/work/Code/IO/src/sitkImageReaderBase.cxx:82:
sitk::ERROR: Unable to determine ImageIO reader for "/mnt/cc7fd727-39d5-4b8f-90d3-c033854aba68/wxy/数据集/pddca18/0522c0330/structures/BrainStem_crp.npy"

**Comment by wentaozhu** [comment]
For .npy, it should be read by numpy, not simpleitk.

**Comment by wwwwwuxueyu** [comment]
这就是我想问的，那代码里应该修改成什么样呀

发自我的iPhone

**Comment by wentaozhu** [comment]
Find the line, then change to np.read()

**Comment by wwwwwuxueyu** [comment]
我想请问一下 代码里cet_path pet_path是什么意思啊

发自我的iPhone

**Comment by wentaozhu** [comment]
We use three datasets. You can get our collected three datasets from https://github.com/wentaozhu/AnatomyNet-for-anatomical-segmentation/blob/master/README.md
There are dataset paths.

**Comment by wwwwwuxueyu** [comment]
如果我想训练我自己的数据 应该怎么操作呀


发自我的iPhone

**Comment by wentaozhu** [comment]
Try to format it as the these datasets.

**Comment by wwwwwuxueyu** [comment]
您好 关于稀疏标签的问题 我在代码上没看明白是那部分的代码实现的 您能指导我一下嘛

发自我的iPhone

**Comment by wentaozhu** [comment]
We use an indicator vector flagvect in https://github.com/wentaozhu/AnatomyNet-for-anatomical-segmentation/blob/master/src/AnatomyNet.py#L225

**Comment by wwwwwuxueyu** [comment]
您好 我想请问一些 代码里.pth文件里 是什么内容呀 方便发一份给我看看吗

发自我的iPhone

**Comment by wentaozhu** [comment]
It is generated automatically if you run the script. You can get the re-implementation from https://github.com/Project-MONAI/MONAI/tree/master/research/lamp-automated-model-parallelism
