### ISSUE TITLE
What`s the difference between *_crp.npy and *_crp_v2.npy ?

### ISSUE THREAD

**Issue by ducheng678** [wentaozhu/AnatomyNet-for-anatomical-segmentation#2]
There is no code for generating *_crp_v2.npy. I would not like to directly use files downloaded from google drive.

**Comment by wentaozhu** [comment]
preprocess_crop.ipynb is the script to crop the head and neck area from the download CT images.

**Comment by ducheng678** [comment]
In preprocess_crop.ipynb, the processed images are saved by the following script "np.save(path+fnm+'/img_crp.npy', nparr)". 
While in AnatomyNet.py image data are loaded by the code "data.append(os.path.join(pth, 'img_crp_v2.npy'))"
Do you mean *_crp.npy and *_crp_v2.npy are the same thing?

**Comment by wentaozhu** [comment]
I think so.
