### ISSUE TITLE
about model file 

### ISSUE THREAD

**Issue by Aaron1993** [wentaozhu/AnatomyNet-for-anatomical-segmentation#20]
hi! in the file ./src/*.py, there are 4 PATH, like 
`TRAIN_PATH = './data/trainpddca15_crp_v2_pool1.pth' 
TEST_PATH = './data/testpddca15_crp_v2_pool1.pth'
CET_PATH = './data/trainpddca15_cet_crp_v2_pool1.pth'
PET_PATH = './data/trainpddca15_pet_crp_v2_pool1.pth'`
how can i generate above 4 PATH? thanks.

**Comment by wentaozhu** [comment]
I think you get to know these paths. It is the dataset paths after you download the data from "The data spliting is in https://www.google.com/search?q=PDDCA+dataset&oq=PDDCA+dataset&aqs=chrome..69i57j0l5.3910j0j7&sourceid=chrome&ie=UTF-8

./data/*.csv files are used to remove non-head and neck regions. Processed PDDCA, PETCT and CET datasets can be downloaded from https://drive.google.com/open?id=1yTarwj5_rp7eX2gCm5k8R0RsZVGzdYlc https://drive.google.com/file/d/17SUj2Si3eD8BHQ7nGpPSO_6wSLlk0TEg/view?usp=sharing https://drive.google.com/file/d/1XbsHVVtap72qp11Pv2cUzbV3dosOjBos/view?usp=sharing"
