### ISSUE TITLE
How to remove CT scanner artifacts from the images

### ISSUE THREAD

**Issue by MrinalJain17** [wentaozhu/AnatomyNet-for-anatomical-segmentation#21]
Hi,

I was using the same dataset, and I wanted to know how did you deal with the artifacts of the CT scanner in the scans. For example:

![image](https://user-images.githubusercontent.com/19644085/96079822-ba0f4680-0e83-11eb-8fa2-d7d18bc9af28.png)

This is a cropped image, but even then, there are some remnants of the CT scanner itself towards the right of the image.

Did you apply any pre-processing to deal with these (apart from cropping)? If not, were the models robust enough to not use them as potential shortcuts?

**Comment by wentaozhu** [comment]
No. I did not do any pre-processing for these artifacts. The model is very robust to these artifacts.

**Comment by MrinalJain17** [comment]
Thanks!
