### ISSUE TITLE
How could I get the pretrained model ?

### ISSUE THREAD

**Issue by ducheng678** [wentaozhu/AnatomyNet-for-anatomical-segmentation#3]
No such file or directory: './model/unet10pool3e2e_seres18_conc_pet_wmask_2_rmsp_1

**Comment by wentaozhu** [comment]
I am sorry that I cannot put these weights into the repository because of big memory size. But you can get it by training https://github.com/wentaozhu/AnatomyNet-for-anatomical-segmentation/blob/master/src/baselineSERes18Conc.py.

**Comment by ducheng678** [comment]
Thanks a lot.
