### ISSUE TITLE
Why you manually set the crop boundary ?

### ISSUE THREAD

**Issue by ducheng678** [wentaozhu/AnatomyNet-for-anatomical-segmentation#4]
Hi, in preprocess_crop.ipynb,
why you manually set the crop boundary as 
"minz, maxz, miny, maxy, minx, maxx = 35, 90, 90, 300, 170, 350" instead of using calculated result.
And then you just compare these two results to ensure that manual setting is right.

**Comment by wentaozhu** [comment]
Because in the test, we do not have the ground truth to calculate the box.

**Comment by ducheng678** [comment]
I mean, in the case that AnatomyNet is a fully convolution network, we do not need to introduce a fixed boundary.

**Comment by wentaozhu** [comment]
We are doing head and neck segmentation. The given images have chest which is useless.
