### ISSUE TITLE
Loss function issue

### ISSUE THREAD

**Issue by ducheng678** [wentaozhu/AnatomyNet-for-anatomical-segmentation#5]
Hi.
I saw that you use the tversky loss in scripts. 
Is it same as the hybrid loss mentioned in paper ?

**Comment by wentaozhu** [comment]
You may read the paper for details https://www.researchgate.net/profile/Wentao_Zhu4/publication/329224429_AnatomyNet_Deep_Learning_for_Fast_and_Fully_Automated_Whole-volume_Segmentation_of_Head_and_Neck_Anatomy/links/5c075ae4458515ae5447b0eb/AnatomyNet-Deep-Learning-for-Fast-and-Fully-Automated-Whole-volume-Segmentation-of-Head-and-Neck-Anatomy.pdf

The script is just for reference.

**Comment by ducheng678** [comment]
ok

**Comment by wwwwwuxueyu** [comment]
> 你好
> 我看到您在脚本中使用了tversky损失。
> 与论文中提到的混合损失相同吗？

I have a problem when running the code, I want to ask you

**Comment by wentaozhu** [comment]
It is in https://github.com/wentaozhu/AnatomyNet-for-anatomical-segmentation/blob/master/src/AnatomyNet.py#L509
