### ISSUE TITLE
about lung nodule/tumor segmentation

### ISSUE THREAD

**Issue by GuobinZhangTJU** [wentaozhu/AnatomyNet-for-anatomical-segmentation#9]
Dear doctor Zhu, sorry to disturb you. my master advisor ask me to segment lung nodules/tumors based on LIDC-IDIR database, can you give me some suggestions in pre-processing data and training? many thanks~

**Comment by wentaozhu** [comment]
You may use the pre-processing on LIDC-IDRI from https://github.com/wentaozhu/DeepLung

**Comment by NotMatter** [comment]
in your nodule detection and classification, the input data is cropped CT image data, i don't the input of tumor segmentation network is also cropped CT image data or only turmor area (extracted according to annoations)? many thanks.

**Comment by GuobinZhangTJU** [comment]
in your nodule detection and classification, the input data is cropped CT image data, i don't know the input of tumor segmentation network is also cropped CT image data or only turmor area (extracted according to annoations)? many thanks.

**Comment by wentaozhu** [comment]
The deeplung crop is to crop the lung region so you can still use it. Please cite our papers if they are helpful. Thank you!

**Comment by GuobinZhangTJU** [comment]
ok, many thanks. thank you ~
